[11.0][T771] - Added Travis files
qrtl/sst-custom pull request #268
Opened 2020-04-21 13:11 UTC by YogeshMahera-SerpentCS

- Task [771](https://www.quartile.co/web#id=844&action=771&model=project.task&view_type=form&menu_id=505)

2020-04-23 09:24 UTC, TimLai125 requested changes

2020-04-23 09:24 UTC, TimLai125 commented on .travis.yml
> +    - EXCLUDE="partner_category_hierarchy,website_forum_visibility"
@YogeshMahera-SerpentCS Please remove this.

2020-04-23 09:24 UTC, TimLai125 commented on .travis.yml
> +        - TESTS="1" ODOO_REPO="OCA/OCB" TEST_ENABLE="0" EXCLUDE=""
install stage is not needed.

2020-04-27 05:02 UTC, YogeshMahera-SerpentCS commented
Hi @TimLai125 Amended Changes

2020-04-27 05:13 UTC, YogeshMahera-SerpentCS commented
@TimLai125 @yostashiro Could you please review it?

2020-06-24 06:46 UTC, YogeshMahera-SerpentCS commented
@TimLai125 Test Comment

2020-07-15 06:12 UTC, merged