[844]- Reformat the code for Quartile Modules.
qrtl/sst-custom pull request #278
Opened 2020-07-16 06:00 UTC by YogeshMahera-SerpentCS

- Task [[844](https://www.quartile.co/web#id=844&action=771&model=project.task&view_type=form&menu_id=505)]
- Closed PR #269

2020-07-17 06:31 UTC, TimLai125 requested changes

2020-07-17 06:31 UTC, TimLai125 commented on .travis.yml
> +    - EXCLUDE="odoo_marketplace,connector_odoo_sst,restful,component_event,access_apps,base_technical_features,drag-and-drop,mail_bcc,web_responsive,access_restricted,component,ir_rule_protected,queu
@YogeshMahera-SerpentCS Please minimize the `Exclude` and put the failed test method as reference if it is inside the `Exclude`.

2020-07-17 16:45 UTC, YogeshMahera-SerpentCS commented
Hi @TimLai125 updated changes can you review it?

2020-07-21 07:40 UTC, TimLai125 requested changes
Github does not recognize some of the python files, @YogeshMahera-SerpentCS  any idea?
Please remove the "description" in the `__manifest__.py` in case the description is already in the README.rst file.

2020-07-21 07:40 UTC, TimLai125 commented on l10n_jp_address_layout/__manifest__.py
> -# -*- coding: utf-8 -*-
This module is an OCA module, i.e. https://github.com/OCA/l10n-japan/tree/11.0/l10n_jp_address_layout
Please exclude it from pre-commit and revert to the original version.

2020-07-21 07:40 UTC, TimLai125 commented on purchase_ext_sst/models/purchase_order_line_hook_onchange_product_id.py
> +# i.e. https://github.com/odoo/odoo/blob/11.0
Please use `# noqa` for this line, we do not want to split links into two lines.

2020-07-21 07:40 UTC, TimLai125 commented on stock_quant_sale_order/wizard/stock_quant_sale_order.py
> +        # product_tax_id = {}
Please delete these lines if the variables are not being used

2020-07-21 07:40 UTC, TimLai125 commented on website_sale_stock_virtual_availability/controllers/main.py
> -    # i.e. https://github.com/odoo/odoo/blob/11.0/addons/website_sale_stock/controllers/main.py#L11-L27
Please apply # noqa as well

2020-07-24 15:47 UTC, YogeshMahera-SerpentCS commented
> Github does not recognize some of the python files, @YogeshMahera-SerpentCS any idea?
Please remove the "description" in the __manifest__.py in case the description is already in the README.rst file.

Hi @TimLai125 I have no idea but maybe there is too many files to check in this PR so maybe that's why. also amended changes.

2020-07-29 06:09 UTC, merged