[844][ADD] Add Test-Case for stock_virtual_available_adj
qrtl/sst-custom pull request #281
Opened 2020-07-21 17:42 UTC by YogeshMahera-SerpentCS

Task #[844](https://www.quartile.co/web#id=844&action=771&model=project.task&view_type=form&menu_id=505)

2020-08-07 09:14 UTC, TimLai125 requested changes

2020-08-07 09:14 UTC, TimLai125 commented on stock_virtual_available_adj/tests/test_product.py
> +                "state": "sent",
Let's make one order to be 'draft'

2020-08-07 09:14 UTC, TimLai125 commented on stock_virtual_available_adj/tests/test_product.py
> +            140,
Why here is 140?

2020-08-07 09:14 UTC, TimLai125 commented on stock_virtual_available_adj/tests/test_product.py
> +            90,
Why here is 90?

2020-08-11 01:51 UTC, yostashiro requested changes
@YogeshMahera-SerpentCS I stopped this review in the middle as the content looks broken in a few places. Please improve the quality to the point it's good for a review.

2020-08-11 01:51 UTC, yostashiro commented on stock_virtual_available_adj/tests/test_product.py
> +        self.stock_location = self.env.ref("stock.stock_location_stock")
```suggestion
        stock_location = self.env.ref("stock.stock_location_stock")
```

Avoid attaching the value to self unless it's necessary.

2020-08-11 01:51 UTC, yostashiro commented on stock_virtual_available_adj/tests/test_product.py
> +            self.product_01, self.stock_location, 100
```suggestion
            self.product_01, stock_location, 100
```

2020-08-11 01:51 UTC, yostashiro commented on stock_virtual_available_adj/tests/test_product.py
> +            self.product_02, self.stock_location, 100
```suggestion
            self.product_02, stock_location, 100
```

2020-08-11 01:51 UTC, yostashiro commented on stock_virtual_available_adj/tests/test_product.py
> +        self.sale_order_line = self.env["sale.order.line"]
```suggestion
```
It's pointless to declare this when it doesn't contribute to simplify/shorten the code.

2020-08-11 01:51 UTC, yostashiro commented on stock_virtual_available_adj/tests/test_product.py
> +        self.product_uom = self.env.ref("product.product_uom_unit").id
```suggestion
        self.product_uom_id = self.env.ref("product.product_uom_unit").id
```
According to https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#variable-names.

2020-08-11 01:51 UTC, yostashiro commented on stock_virtual_available_adj/tests/test_product.py
> +    """
```suggestion
```
I think we should remove this comment as it's not carrying much meaningful message.

2020-08-11 01:51 UTC, yostashiro commented on stock_virtual_available_adj/tests/test_product.py
> +        # `sent` state and compute their quantity.
Consolidate the comments. The bottom sentence looks broken.

2020-08-11 01:51 UTC, yostashiro commented on stock_virtual_available_adj/tests/test_product.py
> +                "state": "draft",
In reality you can't apply different states to lines under the same order. We should create a separate sales order as necessary.

2020-08-11 01:51 UTC, yostashiro commented on stock_virtual_available_adj/tests/test_product.py
> +        self.product_01._compute_sale_quantities()
Why are products inconsistent here?

Besides, you should not have to call `_compute_sale_quantities` method here (I think you keep making the same mistake of calling methods unnecessarily in tests).

2020-08-12 10:29 UTC, merged