[896][IMP] Add mail_outbound_static as dependency
qrtl/sst-custom pull request #288
Opened 2020-10-14 06:21 UTC by TimLai125

#[896](https://www.quartile.co/web?debug=#id=896&action=771&model=project.task&view_type=form&menu_id=505)

2020-10-14 06:22 UTC, TimLai125 commented
The branch to be rebased after https://github.com/qrtl/sst-custom/pull/287 is maerged

2020-10-19 15:22 UTC, yostashiro approved these changes
LGTM, but please also add applicable changes from https://github.com/qrtl/sst-custom/pull/289.

2020-10-24 07:28 UTC, yostashiro requested changes

2020-10-24 07:28 UTC, yostashiro commented on website_forum_adj/README.rst
> +    :target: https://github.com/qrtl/sst-custom/tree/12.0/website_forum_adj
Why 12.0?

2020-10-24 07:28 UTC, yostashiro commented on website_forum_adj/README.rst
> +This module is part of the `qrtl/sst-custom <https://github.com/qrtl/sst-custom/tree/12.0/website_forum_adj>`_ project on GitHub.
Why 12.0?

2021-03-31 07:27 UTC, TimLai125 commented
Drop this PR since the logic will be generalized in https://github.com/qrtl/sst-custom/pull/289

2021-03-31 07:27 UTC, closed without merging