[3152][ADD] account_invoice_delivered_amount
qrtl/sst-custom pull request #317
Opened 2023-01-31 05:02 UTC by AungKoKoLin1997

[3152](https://www.quartile.co/web#id=3152&action=771&model=project.task&view_type=form&menu_id=505)

2023-01-31 05:03 UTC, AungKoKoLin1997 commented
@kanda999  Can you please review first this PR?

2023-01-31 05:09 UTC, yostashiro requested changes
@AungKoKoLin1997 Haven't checked in detail, but we need a pre_init_hook for sure.  It is a large database.  Can you try and include the SQL to update the existing records?  If it's too complecated, please do not use much time on this and just create new columns in pre_init_hook to avoid computation at install.

2023-01-31 05:09 UTC, yostashiro commented on account_invoice_delivered_amount/models/account_invoice_line.py
> +    @api.depends("sale_line_ids", "product_id", "quantity")
Listen to the specific field of sale.order.line.  We need to watch the delivered qty field.

2023-01-31 05:34 UTC, kanda999 requested changes
Function was not complete.
As tashiro-san commented, if the invoice was created and then delivered, the delivered totals and is_delivered needed to be updated.

2023-01-31 07:55 UTC, kanda999 requested changes
@AungKoKoLin1997 
I tried to install, but the existing data is not updated.  Am I making any mistakes?

2023-01-31 08:00 UTC, AungKoKoLin1997 commented
> @AungKoKoLin1997 I tried to install, but the existing data is not updated. Am I making any mistakes?

No. In the first installation, I made to avoid computing for large database.

> If it's too complecated, please do not use much time on this and just create new columns in pre_init_hook to avoid computation at install.

2023-01-31 08:03 UTC, kanda999 commented
> No. In the first installation, I made to avoid computing for large database.

Sorry I got it.  So how should existing data be updated?

2023-01-31 08:07 UTC, AungKoKoLin1997 commented
> So how should existing data be updated?

I still have no idea. I haven't never written sql for updating existing records at install and I am worried it will take much time. It will be nice if you know how to do it.

2023-01-31 08:15 UTC, kanda999 commented
@AungKoKoLin1997 
I asked the client about the need for existing data calicuration.

2023-01-31 08:17 UTC, AungKoKoLin1997 commented
> @AungKoKoLin1997 I asked the client about the need for existing data calicuration.

Sorry. I am not clear. Do you mean client also want to update data for the existing records?

2023-01-31 08:21 UTC, kanda999 commented
I mean I'm communicating if the client needs it or not.

2023-01-31 08:47 UTC, kanda999 approved these changes
Function review

2023-01-31 09:27 UTC, yostashiro requested changes
Please extend the account invoice search for the tree view to allow filtering records by "Delivered".

2023-01-31 09:27 UTC, yostashiro commented on account_invoice_delivered_amount/models/account_invoice_line.py
> +                line.deliverd_amount = 0
```suggestion
    @api.depends("quantity", "price_unit", "sale_line_ids.qty_delivered")
    def _compute_delivered_amount(self):
        for line in self:
            if line.product_id.type == "service" or not line.sale_line_ids:
                line.is_delivered = True
                line.deliverd_amount = line.quantity * line.price_unit
                continue
            qty_delivered = sum(line.sale_line_ids.mapped("qty_delivered"))
            if qty_delivered > 0:
                line.is_delivered = True
                line.deliverd_amount = qty_delivered * line.price_unit
```
We will always treat services and credit notes as "delivered."

2023-01-31 09:27 UTC, yostashiro commented on account_invoice_delivered_amount/models/account_invoice.py
> +        currency_field="company_currency_id",
```suggestion
```
Why `company_currency_id here`?

2023-01-31 09:27 UTC, yostashiro commented on account_invoice_delivered_amount/views/account_invoice_views.xml
> +                <field name="total_delivered_amount_signed" attrs="{'invisible': [('type','!=','out_invoice')]}" string="Total Delivered" sum="Total" />
```suggestion
                <field name="total_delivered_amount_signed" string="Total Delivered" sum="Total" />
```
The field should show for credit notes as well.

2023-01-31 09:27 UTC, yostashiro commented on account_invoice_delivered_amount/models/account_invoice.py
> +        currency_field="currency_id",
```suggestion
```

2023-01-31 09:27 UTC, yostashiro commented on account_invoice_delivered_amount/models/account_invoice.py
> +    total_delivered_amount = fields.Monetary(
```suggestion
    amount_total_delivered = fields.Monetary(
```
Following the convention of other amount_xxx fields.

2023-01-31 09:27 UTC, yostashiro commented on account_invoice_delivered_amount/models/account_invoice.py
> +    total_delivered_amount_signed = fields.Monetary(
```suggestion
    amount_total_delivered_signed = fields.Monetary(
```

2023-01-31 09:27 UTC, yostashiro commented on account_invoice_delivered_amount/models/account_invoice.py
> +            invoice.total_delivered_amount_signed = total_delivered_amount_signed
```suggestion
    @api.depends("invoice_line_ids.is_delivered", "invoice_line_ids.deliverd_amount", "type")
    def _compute_amount_delivered(self):
        for invoice in self:
            if invoice.type not in ["out_invoice", "out_refund"]:
                continue
            sign = -1 if self.type == "out_refund" else 1
            invoice.total_amount_delivered = sum(invoice.invoice_line_ids.mapped("deliverd_amount"))
            invoice.total_amount_delivered_signed = invoice.total_amount_delivered * sign
```

2023-01-31 09:37 UTC, yostashiro commented on account_invoice_delivered_amount/readme/DESCRIPTION.rst
> +This module displays delivered amount in customer invoices.
```suggestion
This module adds delivered amount fields the customer invoice.

We regard service lines and credit notes as "delivered."

Background:

There are cases where user issues an invoice to the customer upfront in a business transaction,
just for the sake of convenience, even when the goods are yet to be delivered to them.
In such case, technically speaking, revenue should not be recognized until the delivery is done.

This module intends to make the "real" sales amount visible in the invoice views by computing
the delivered amount.
```

2023-01-31 09:43 UTC, AungKoKoLin1997 commented on account_invoice_delivered_amount/models/account_invoice.py
> +        currency_field="company_currency_id",
I think we should display the amount in company currency in tree view like other fields(eg . `amount_total_signed`). My intention for creating this field is to display with converted amount in company currency in tree view. If not, we don't even need this field. We can use only `total_delivered_amount` field.

2023-01-31 09:47 UTC, yostashiro commented on account_invoice_delivered_amount/models/account_invoice.py
> +        currency_field="company_currency_id",
If I'm not mistaken, `amount_total_signed` (which shows in the list view) is not in company currency. `amount_total_company_signed` is.

2023-01-31 10:01 UTC, AungKoKoLin1997 commented on account_invoice_delivered_amount/models/account_invoice.py
> +        currency_field="company_currency_id",
Yes. I am confused with version 15. In v15, `amount_total_signed` is defined with company currency.https://github.com/odoo/odoo/blob/d4e322d4bad40f09fd11fd368c1f7e83e3bb7a36/addons/account/models/account_move.py#L246.
My intension for amount_total_signed was to display in company currency. So, should I create new field `amount_total_delivered_company_signed` for displaying with company currency in list view?

2023-01-31 10:04 UTC, yostashiro commented on account_invoice_delivered_amount/models/account_invoice.py
> +        currency_field="company_currency_id",
> So, should I create new field amount_total_delivered_company_signed for displaying with company currency in list view?

No need to do that this time (there is no user demand for it).

2023-01-31 15:50 UTC, yostashiro approved these changes

2023-02-01 04:58 UTC, yostashiro requested changes

2023-02-01 04:58 UTC, yostashiro commented on account_invoice_delivered_amount/models/account_invoice_line.py
> +                line.delivered_amount = line.quantity * line.price_total
```suggestion
                line.delivered_amount = line.price_total
```

2023-02-01 04:58 UTC, yostashiro commented on account_invoice_delivered_amount/models/account_invoice_line.py
> +                line.delivered_amount = qty_delivered * line.price_total
```suggestion
                currency = line.invoice_id and line.invoice_id.currency_id or None
                price = line.price_unit * (1 - (line.discount or 0.0) / 100.0)
                taxes = False
                if line.invoice_line_tax_ids:
                    taxes = line.invoice_line_tax_ids.compute_all(price, currency, line.quantity_delivered, product=line.product_id, partner=line.invoice_id.partner_id)
                delivered_subtotal = taxes["total_excluded"] if taxes else line.quantity_delivered * price
                line.delivered_amount = taxes["total_included"] if taxes else delivered_subtotal
```
To replicate the logic of the standard method https://github.com/odoo/odoo/blob/cd580dd60545766acd0a02ea9dc89e2c9c5de743/addons/account/models/account_invoice.py#L1431-L1437.  A bit more complicated than one would imagine...

2023-02-01 06:27 UTC, yostashiro approved these changes

2023-02-01 06:29 UTC, yostashiro approved these changes

2023-02-02 01:32 UTC, merged