[3308][MIG] website_sale_wishlist_list_view: Migration to 15.0
qrtl/sst-custom pull request #322
Opened 2023-03-16 10:39 UTC by AungKoKoLin1997

[3308](https://www.quartile.co/web#id=3308&action=771&model=project.task&view_type=form&menu_id=505)

2023-03-30 06:59 UTC, yostashiro commented
@AungKoKoLin1997 Two things:

- Can we rename the module to website_sale_wishlist_menuitem
- Do you think it's a good idea to put this module in oca/e-commerce?

2023-03-31 05:11 UTC, AungKoKoLin1997 commented
> Do you think it's a good idea to put this module in oca/e-commerce?

@yostashiro  Yes. I think it's a good idea.

2023-03-31 08:58 UTC, yostashiro requested changes

2023-03-31 08:58 UTC, yostashiro commented on website_sale_wishlist_menuitem/readme/DESCRIPTION.rst
> +* This module adds a menuitem for internal user to check all the wishlist products.
```suggestion
* Adds a menuitem for internal users to be able to check/manage the wishlist content in the backend.
```

2023-03-31 08:58 UTC, yostashiro commented on website_sale_wishlist_menuitem/views/product_wishlist_views.xml
> +        parent="website_sale.menu_catalog"
```suggestion
        parent="website_sale.menu_orders"
```
I think this node would be more appropriate.

2023-03-31 08:58 UTC, yostashiro commented on website_sale_wishlist_menuitem/i18n/ja.po
Please regenerate the translation file, and apply the same translation.  Please ask @rinaldifirdaus to support if you have a difficulty.

2023-03-31 08:58 UTC, yostashiro commented on website_sale_wishlist_menuitem/views/product_wishlist_views.xml
> +                </group>
Let's move this to the bottom inside the search tag, following the convention.

2023-03-31 15:24 UTC, yostashiro approved these changes
Code + functional reviews. 👍 

@AungKoKoLin1997 Please go ahead and create a PR in oca/e-commerce.

2023-03-31 15:25 UTC, merged