[3303][MIG] hr_attendance_rest_time: Migration to 15.0
qrtl/sst-custom pull request #325
Opened 2023-03-20 08:57 UTC by AungKoKoLin1997

[3303](https://www.quartile.co/web#id=3303&action=771&model=project.task&view_type=form&menu_id=505)

2023-03-23 07:10 UTC, yostashiro requested changes

2023-03-23 07:10 UTC, yostashiro commented on hr_attendance_rest_time/models/hr_attendance.py
> +        self.work_location_id = employee.work_location_id.id if employee else False
```suggestion
        self.work_location_id = employee.work_location_id if employee else False
```

2023-03-23 07:10 UTC, yostashiro commented on hr_attendance_rest_time/readme/DESCRIPTION.rst
> +  - Category, Rest Time, Manual Update Flag, Reason for Manual Update
```suggestion

  - Category, Rest Time, Manual Update Flag, Reason for Manual Update
```

2023-03-23 08:57 UTC, yostashiro approved these changes

2023-08-19 07:15 UTC, rinaldifirdaus approved these changes
Test the functions of this module. works as expected!
- rest time proposed on attendance
- manual update flag and reason displayed on the manual creation of attendance form
<img width="449" alt="image" src="https://github.com/qrtl/sst-custom/assets/122415281/79c59409-4d9c-4d29-815c-d4f32727da6d">
<img width="880" alt="image" src="https://github.com/qrtl/sst-custom/assets/122415281/45a14fdd-fc1d-4478-8a7c-9e44956d6652">

2023-11-09 10:15 UTC, kanda999 commented
The PR is used by rmm-custom: https://github.com/qrtl/rmm-custom/pull/80

2023-11-09 10:15 UTC, closed without merging