[3361][MIG] website_sale_wishlist_archive_cron: Migration to 15.0
qrtl/sst-custom pull request #327
Opened 2023-04-06 07:21 UTC by AungKoKoLin1997

[3361](https://www.quartile.co/web#view_type=form&model=project.task&id=3361&active_id=3361&menu_id=)

2023-04-06 10:00 UTC, yostashiro requested changes
Rather minor suggestion.

2023-04-06 10:00 UTC, yostashiro commented on website_sale_wishlist_archive_cron/models/product_wishlist.py
> +                record.active = False
```suggestion
        wishlist_records_to_archive = wishlist_records.filtered(lambda x: not x.product_id.active)
        wishlist_records_to_archive.write({"active": False})
```

2023-04-06 10:02 UTC, yostashiro commented
@rinaldifirdaus Can you please double check the necessity of this module, according to the 15.0 functions (make sure that the same function does not exist).

2023-04-06 10:07 UTC, AungKoKoLin1997 commented
@rinaldifirdaus FYI, in odoo15, there is no function for auto archive for wishlist when archive the product but I didn’t check the cron job.

2023-04-07 00:42 UTC, yostashiro approved these changes

2023-05-12 09:51 UTC, kanda999 approved these changes
This is the functionality you get this module; the default Odoo15 does not have the same functionality.

2023-06-22 07:22 UTC, merged