[3548][IMP] product_yahoo_auction_sst: change char fields to many2one
qrtl/sst-custom pull request #342
Opened 2023-07-14 02:53 UTC by AungKoKoLin1997

[3548](https://www.quartile.co/web?#id=3548&action=771&model=project.task&view_type=form&menu_id=505)

2023-07-14 03:13 UTC, yostashiro reviewed
Partial review.

2023-07-14 03:13 UTC, yostashiro commented on product_yahoo_auction_sst/models/deliver_prefecture.py
> +    name = fields.Char(string='Prefecture Name', required=True)
Shouldn't we extend `res.country.state` instead by adding `is_deliverable` boolean field, perhaps?

2023-07-14 03:13 UTC, yostashiro commented on product_yahoo_auction_sst/models/delivery_city.py
> +    name = fields.Char(string='City Name', required=True)
Add `state_id` with many2one relation to `res.country.state`.

2023-07-14 03:16 UTC, yostashiro commented
@kanda999 Shouldn't this actually be a separate module to product_yahoo_auction_sst?

2023-07-18 02:57 UTC, kanda999 commented
@AungKoKoLin1997 
I checked with the customer and they said that the view of list may be changed.
So please adjust this PR function as sperate module.

2023-07-18 05:47 UTC, AungKoKoLin1997 commented
@kanda999  Please review this PR and let me know if you have any better module name.

2023-07-19 02:58 UTC, yostashiro requested changes
Why mix words `deliver` and `delivery`?  Please be strict and consistent with word choices.

2023-07-19 02:58 UTC, yostashiro commented on delivery_information/__manifest__.py
Please rename the module to `product_delivery_destination`.

@kanda999 Please make a counter-suggestion if you can think of a better name.

2023-07-19 09:40 UTC, yostashiro requested changes

2023-07-19 09:40 UTC, yostashiro commented on product_delivery_destination/__manifest__.py
> +    "depends": ["base", "product"],
```suggestion
    "depends": ["product"],
```

2023-07-19 09:40 UTC, yostashiro commented on product_delivery_destination/models/product_template.py
> +    delivery_city = fields.Many2one('delivery.city', string="Delivery City")
To follow the standard naming rule.

```suggestion
    delivery_state_id = fields.Many2one('res.country.state', string="Delivery Prefecture", domain="[('is_deliverable','=', True)]")
    delivery_city_id = fields.Many2one('delivery.city', string="Delivery City")
```

2023-07-19 09:40 UTC, yostashiro commented on product_delivery_destination/readme/DESCRIPTION.rst
> +associated with the state and city.
```suggestion
This module adds state and city many2one fields to the product model.

These fields are expected to be used to keep the information necessary for listing products in an external auction/marketplace website.
```

2023-07-20 14:00 UTC, yostashiro reviewed
Please add CONFIGURE.rst as well with a short explanation.

2023-07-20 14:00 UTC, yostashiro commented on product_delivery_destination/models/product_template.py
> +            return {'domain': {'delivery_city_id': []}}
I missed to comment about this earlier. It's not a good practice to manipulate wiht the domain with an onchange method, as the domain doesn't stick when the view is reloaded.

We may consider to do something like this instead: https://github.com/OCA/bank-payment/pull/1106/commits/3955f46146919e60bb9d91ad91a1542c7796a835#diff-40552b82ea2aa604c7524ad4e88fb50e0afc7f780d70e3bafe4336444aec2c79R74-R87

2023-07-21 03:09 UTC, yostashiro approved these changes
Code review.

2023-07-26 09:34 UTC, kanda999 approved these changes
Functional review. It works as expected

2023-07-27 05:46 UTC, merged