[3625][ADD] account_invoice_validation_adj
qrtl/sst-custom pull request #351
Opened 2023-08-31 08:39 UTC by AungKoKoLin1997

[3625](https://www.quartile.co/web#id=3625&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)

2023-08-31 15:21 UTC, yostashiro requested changes
Please split the module into two:

- product_group_manage_product
- account_security_adj

2023-09-04 03:40 UTC, yostashiro requested changes

2023-09-04 03:40 UTC, yostashiro commented on product_group_manage_product/security/product_group_manage_product_security.xml
> +    </record>
Why do we need these record rules?

2023-09-04 03:40 UTC, yostashiro commented on product_group_manage_product/security/ir.model.access.csv
> +access_product_product,access_product_product,product.model_product_product,group_manage_product,1,1,1,0
Any reason why `perm_unlink` should be false?
```suggestion
access_product_template_manage_product,product.template.manage.product,product.model_product_template,group_manage_product,1,1,1,1
access_product_product_manage_product,product.product.manage.product,product.model_product_product,group_manage_product,1,1,1,1
```

2023-09-04 03:40 UTC, yostashiro commented on product_group_manage_product/__manifest__.py
> +    "license": "LGPL-3",
```suggestion
    "license": "AGPL-3",
```

2023-09-07 07:30 UTC, yostashiro reviewed
I've come to think `product_group_product_manager` might be a better choice for the module name (upon changing the technical name of the module).  What do you think?

2023-09-07 07:30 UTC, yostashiro commented on product_group_manage_product/security/product_group_manage_product_security.xml
> +        <field name="name">Product Creation, Editing &amp; Deletion</field>
```suggestion
        <field name="name">Product Manager</field>
```

2023-09-07 07:40 UTC, AungKoKoLin1997 commented
> I've come to think `product_group_product_manager` might be a better choice for the module name (upon changing the technical name of the module). What do you think?

Yes. `product_group_product_manager` is better module name and can easily know this module is added new group `group_product_manager`.

2023-09-07 08:24 UTC, yostashiro approved these changes
Code review.  Thanks Lin!

2023-09-07 08:24 UTC, yostashiro commented on product_group_product_manager/readme/DESCRIPTION.rst
> +This module adds a new group (group_manage_product) with permissions for creating, editing, and deleting products.
```suggestion
This module adds a new group (group_product_manager) with permissions for creating, editing, and deleting products.
```

2023-10-26 09:59 UTC, kanda999 requested changes
@AungKoKoLin1997 
I have found that if product manager don't have access to the product.price.history model, they get an error when they try to create a new product from sale.order.line or purchase.order.line.

So can product_manager please allow read write update delete of product.price.history?

2023-10-27 02:53 UTC, kanda999 approved these changes
Function, code review

2023-10-27 03:01 UTC, merged