[11.0][3625][ADD] account_security_adj
qrtl/sst-custom pull request #352
Opened 2023-09-01 02:21 UTC by AungKoKoLin1997

[3625](https://www.quartile.co/web#id=3625&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)

2023-09-04 03:45 UTC, yostashiro requested changes
Please add CONTEXT.rst, mentioning that the adjustments of this module is not required in newer versions.

Please add the setup file.

2023-09-04 03:45 UTC, yostashiro commented on account_security_adj/__manifest__.py
> +    "license": "LGPL-3",
```suggestion
    "license": "AGPL-3",
```

2023-09-06 02:22 UTC, AungKoKoLin1997 commented
> Please add CONTEXT.rst, mentioning that the adjustments of this module is not required in newer versions.

Sorry. I don't get the point. Why this adjustment is not required in newer versions? `confirm` button is allowed to group_account_invoice in newer version.

2023-09-06 02:41 UTC, yostashiro commented
@AungKoKoLin1997 My bad. Please forget about the context file.

2023-10-05 10:29 UTC, yostashiro commented on account_security_adj/readme/DESCRIPTION.rst
> +This module restricts the validation of customer invoices and vendor bills to the group_account_manager group.
@kanda999 Can you update this to reflect the latest design in concise manner.

2023-10-06 02:14 UTC, yostashiro approved these changes

2023-10-27 03:01 UTC, kanda999 approved these changes

2023-10-27 03:01 UTC, merged